version: "3.9"

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=api/model/best.pt
    restart: always
    profiles: ["prod"]

    # Dev-only: mount local code for hot reload
    volumes:
      - ./api:/app/api

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
    profiles: ["prod"]
