version: "3.9"

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=model/best.pt   # because inside container it’s /app/model
    restart: always
    volumes:
      - ./api:/app   # optional hot reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
