name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./api                # ✅ make sure this is where app.py lives
          file: ./api/Dockerfile        # ✅ be explicit, avoids confusion
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/underwater_waste_detection-backend:latest
            ghcr.io/${{ github.repository_owner }}/underwater_waste_detection-backend:${{ github.sha }}

  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile   # ✅ explicitly point to Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/underwater_waste_detection-frontend:latest
            ghcr.io/${{ github.repository_owner }}/underwater_waste_detection-frontend:${{ github.sha }}
