name: CI Pipeline

on:
  push:
    branches: [ "main" ]   # runs when you push to main
  pull_request:
    branches: [ "main" ]   # runs when a PR targets main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd api
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend health check
        run: |
          python -m flask --app api/app.py --debug run &
          sleep 5
          curl http://127.0.0.1:5000/health || exit 1
